### ISSUE TITLE
module queries no longer return module doc

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-module-resolver#111]
So it seems to me that this isn't a bug in the IDE. It looks like the CMR suddenly stopped sending module docs with query results. This is a pretty serious bug, affecting the Repository Explorer, New Module wizard, and Module properties page.

**Comment by alesj** [comment]
@quintesse / @FroMage so this is already fixed?
@gavinking ^^

**Comment by FroMage** [comment]
No idea.

**Comment by gavinking** [comment]
I agree, it looks fixed to me.
