### ISSUE TITLE
Reporting SocketTimeoutException without host

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-module-resolver#124]
For some unknown reason I've been having trouble getting artifacts from modules.ceylon-lang.org. The errors from the CMR have not been helpful, for example

    ../ceylon-sdk/test-source/test/ceylon/net/module.ceylon:11: error: cannot find module artifact io.netty-4.0.2.Final.jar
    import io.netty "4.0.2.Final";
    ^
    due to connection error: java.net.SocketTimeoutException: Read timed out
    
      - dependency tree: test.ceylon.net/1.1.1 -> io.netty/4.0.2.Final

It doesn't say what host it's trying to download netty from. To find out I have to compile using the CLI with `--verbose`, and doing that isn't always simple (e.g. you have a complex build). At a mimimum the message should include the hostname and ideally the complete URL, imo.

**Comment by FroMage** [comment]
Do you happen to have the stack trace?

**Comment by tombentley** [comment]
No, there was no stacktrace, it was a nicely formatted message as above.

**Comment by FroMage** [comment]
Can you use your debugger then? I suspect there are many places where this can happen: DNS, initial connection, reads…

Apparently I should be able to simulate timeouts by setting one as low as 1ms. I can try that, too.

**Comment by tombentley** [comment]
Oh another problem I had was sometimes it would fetch part of the jar, and then die leaving a corrupt jar on the filesystem. On the next run it fell over with an error about an unreadable zip file. I guess that's a separate issue though.

**Comment by FroMage** [comment]
Yes please report that too, we should catch that and delete the file. Or resume, I suppose.

**Comment by FroMage** [comment]
Fixed.
