### ISSUE TITLE
Corrupt jars files following SocketTimeoutException

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-module-resolver#125]
If a `SocketTimeoutException` occurs when downloading a jar from a remote repo it seems that the partially transferred file is left of the filesystem. On a subsequent run things break because the zip file is invalid.

**Comment by tombentley** [comment]
Maybe we should write to a `foo-1.0.0.jar.part` file and rename it when the download is complete. That would also allow us to resume a transfer using a range request.

**Comment by FroMage** [comment]
Fixed. We'll implement partial files and resuming later, it's not a priority since most files are small, and I expect we'll need parallel downloads too later.
