### ISSUE TITLE
ModuleVersionDetails should include information about what backends the module supports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-module-resolver#128]
I tried to figure out the backends for a `ModuleVersionDetails` by iterating the `artifactTypes`, but that didn't work at all, because it only returned `.car` for `ceylon.collection`. (This seems like a bug, FTR.)

Anyway, I think it should be able to give me a list of backends.

**Comment by quintesse** [comment]
If I type `ceylon info ceylon.collection/1.1.1` on the command line it gives me:

    Artifacts:   JavaScript (#8), JVM (#8), Sources

So I'm sure it must be possible. What is perhaps counterintuitive is the if you ask for JVM artifacts the above list will suddenly only show `JVM`, even though a `JS` version of `ceylon.collection` exists.

**Comment by gavinking** [comment]
@quintesse I'm asking for artifacts of type `CODE`.

**Comment by gavinking** [comment]
@quintesse please look at the branch `native_module_imports` of the IDE, in particular at `ModuleSearchManager.convertResult()`, which is not working because CMR is not returning the expected artifact types.

**Comment by FroMage** [comment]
@gavinking apparently `completeVersions` does what you want, but not `searchModules`. Are you using the latter perhaps?

**Comment by gavinking** [comment]
I'm using `completeModules()`, I think.

**Comment by FroMage** [comment]
Nope, that one doesn't do it. I wonder what the logic is.

**Comment by FroMage** [comment]
I'll take this.

**Comment by FroMage** [comment]
Mmm, now that I read every artifact that we want, I'm not reading the `.car` when we ask for JS only, which means we don't get the docs because we can't extract that from the JS model yet. Damn.

**Comment by FroMage** [comment]
Done.

**Comment by gavinking** [comment]
Well, sorry, @FroMage, but this doesn't help me. Now it tells me that `ceylon.collection` is `native("jvm")`, which of course it's not.

**Comment by gavinking** [comment]
Hrm, or at least that's what it says if I set `ModuleQuery.Type.JVM`.

**Comment by gavinking** [comment]
Oh I see. The thing is that the `ModuleDetails` doesn't actually tell me about the `native` backend at all. It just sends me artifacts. And I use that to infer the backend type. So I guess I need a new `nativeBackends` attribute on `ModuleDetails`.

**Comment by FroMage** [comment]
Right, native is something else. Please open another issue and assign it to @quintesse ;)
